"""Update feedback uniqueness constraint to include model_used

Revision ID: cdef4f3bbcf8
Revises: e5f944fae805
Create Date: 2025-04-30 13:21:45.443958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdef4f3bbcf8'
down_revision = 'e5f944fae805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_item_model_feedback', ['user_id', 'item_title', 'model_used'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_item_model_feedback', type_='unique')

    # ### end Alembic commands ###
