"""Add model_used field to Feedback model

Revision ID: e5f944fae805
Revises: 65f358281927
Create Date: 2025-04-10 11:13:35.612225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f944fae805'
down_revision = '65f358281927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_item_feedback', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_item_feedback', ['user_id', 'item_title'])

    # ### end Alembic commands ###
